<?php
global $revechat_options;
if (!isset($revechat_options)){
	$revechat_model = Mage::getModel('revechat/revechat')->load(1);
	$revechat_options = $revechat_model->_data;
}
?>

<?php if($revechat_options['revechat_aid'] != null){

	?>
 <!-- Start of REVE Chat Script-->
 <script type='text/javascript'>
 window.__revechat_account = window.__revechat_account || {};
 window.__revechat_account = '<?php echo $revechat_options['revechat_aid']; ?>';
 (function() { 
   var rc = document.createElement('script'); rc.type = 'text/javascript'; rc.async = true;
   rc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'static.revechat.com/widget/scripts/new-livechat.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(rc, s);
})();
</script>
<!-- End of REVE Chat Script -->

<?php } ?>